views:
  - title: Chart Test
    panel: true
    cards:
      - type: 'custom:cards-layout'
        title: Auswertung (Header)
        icon: 'mdi:tape-measure'
        description: Hier werden alle Daten in graphischer Form dargestellt
        width: 80%
        cards:
          - row:
              - col: null
                width: 100%
                title: Übersicht - Spalte 1
                description: Übersicht der Auswertung
                entities:
                  - type: picture-glance
                    title: Eingang
                    image: /local/images/rooms/eingang.jpg
                    entities:
                      - sun.sun
          - row:
              - col: null
                width: 50%
                height: 320
                title: Auswertung 1 (4 Spalten - equal height)
                description: Hier werden alle Auswerungen für den Stromverbrauch angezeigt
                entities:
                  - type: 'custom:simple-card'
                    style: >
                      background: rgba(0, 0, 0, 0) linear-gradient(rgb(241, 39,
                      17), rgb(245, 175, 25)) repeat scroll 0% 0%; height: 300px
                    title: Daten 1
                    entities:
                      - sun.sun
                  - type: 'custom:chart-card'
                    title: Chart 1
                    icon: 'mdi:nutrition'
                    height: 240
                    chart: pie
                    options:
                      title:
                        display: true
                        text: Orangenbaum
                    entities:
                      - entity: sensor.orangenbaum_moisture
                      - entity: sensor.orangenbaum_temperature
                      - entity: sensor.orangenbaum_conductivity
                  - type: 'custom:chart-card'
                    style: |
                      background: linear-gradient(to bottom, #009fff, #ec2f4b); 
                      color: #FFFFFF
                    title: Chart 2
                    icon: 'mdi:nutrition'
                    height: 240
                    chart: bar
                    options:
                      title:
                        display: true
                        text: Orangenbaum
                    entities:
                      - entity: sensor.orangenbaum_battery
                      - entity: sensor.orangenbaum_moisture
                      - entity: sensor.orangenbaum_temperature
                      - entity: sensor.orangenbaum_conductivity
                  - type: 'custom:mini-graph-card'
                    height: 193
                    style: >
                      background: linear-gradient(to top, #fc4a1a, #f7b733);
                      color:#FFFFFF
                    entities:
                      - entity: sensor.temperatur_indoor
                        name: Innenraum
                      - entity: sensor.orangenbaum_light
          - row:
              - col: null
                title: Auswertung 2 (3 Spalten)
                description: Hier werden alle Auswerungen für den Wasserverbrauch angezeigt
                entities:
                  - type: markdown
                    style: >
                      height:300px; background: linear-gradient(45deg, #5fc9f8,
                      #fecb2e, #fd9426, #fc3158, #147efb,
                      #53d769);                
                    content: |
                      Hello, {{user}}
                  - type: 'custom:chart-card'
                    title: Chart 3
                    icon: 'mdi:nutrition'
                    height: 240
                    chart: doughnut
                    options:
                      title:
                        display: true
                        text: Orangenbaum
                    entities:
                      - entity: sensor.orangenbaum_moisture
                      - entity: sensor.orangenbaum_temperature
                      - entity: sensor.orangenbaum_conductivity
                  - type: 'custom:chart-card'
                    title: Chart 4
                    icon: 'mdi:nutrition'
                    height: 240
                    chart: pie
                    options:
                      title:
                        display: true
                        text: Orangenbaum
                    entities:
                      - entity: sensor.orangenbaum_moisture
                      - entity: sensor.orangenbaum_temperature
                      - entity: sensor.orangenbaum_conductivity
